import nextPlugin from "@next/eslint-plugin-next";

export default [
  {
    ignores: [".next/**", "coverage/**", "dist/**", "node_modules/**", "out/**"],
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    plugins: {
      "@next/next": nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      "array-callback-return": "error",
      "consistent-return": "error",
      curly: ["error", "all"],
      "default-case-last": "error",
      "dot-notation": "error",
      eqeqeq: ["error", "smart"],
      "no-alert": "warn",
      "no-console": ["warn", { allow: ["error", "warn"] }],
      "no-debugger": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-eval": "error",
      "no-implicit-coercion": ["warn", { allow: ["!!"] }],
      "no-implied-eval": "error",
      "no-lonely-if": "error",
      "no-nested-ternary": "warn",
      "no-new-wrappers": "error",
      "no-promise-executor-return": "error",
      "no-return-await": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "warn",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-var": "error",
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
      "prefer-const": "error",
      "prefer-destructuring": ["warn", { array: false, object: true }],
      "prefer-exponentiation-operator": "error",
      "prefer-object-has-own": "error",
      "prefer-template": "error",
      radix: "error",
      "require-await": "warn",
      "symbol-description": "error",
      yoda: "error",
    },
  },
];
